project:
  type: default
  output-dir: _output
  preview: 
    port: 4444

  render: 
    - "index.qmd"

language: 
  title-block-published: Latest version
  related-formats-title: Other formats
  other-links-title: Other links

format:
  wordcount-html: 
    wordcount-banner: false

    toc: true
    shift-heading-level-by: 1
    theme: 
      - zephyr
      - html/custom.scss
    title-block-banner: "#000D51"
    include-in-header:
      - text: |
          <style type="text/css">
          h2.hide {
            display: none;
          }
          </style>

    format-links:
      - html
      - format: hikmah-pdf
        text: PDF version
        icon: file-pdf

    other-links:
      - text: GitHub repository
        href: https://github.com/andrewheiss/butterscotch-bat/
        icon: github
      - text: SocArXiv preprint
        href: https://doi.org/10.31235/osf.io/9gmhp
        icon: link-45deg
      - text: OSF project
        href: https://doi.org/10.17605/OSF.IO/R97Y3
        icon: link-45deg

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300

  # Nice PDF output
  hikmah-pdf:
    output-file: heiss-chaudhry-donor-responses-chapter.pdf
    # Custom fonts
    mainfont: "Linux Libertine O"
    mainfontoptions:
      - "Numbers=Proportional"
      - "Numbers=OldStyle"
    sansfont: "Inter"
    mathfont: "Libertinus Math"
    # linestretch: 1.05

    knitr:
      opts_chunk:
        dev: "cairo_pdf"
